#!/bin/bash
set -e

# Automatically added by dh_installdocs
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/parted ]; then
  rm -fv /usr/doc/parted
fi

# End automatically added section

