#!/bin/bash

# Version Information
MAJOR=4
MINOR=0
MICRO=5
NANO=0
DEBIAN_VERSION=1
VERSION=${MAJOR}.${MINOR}.${MICRO}.${NANO}

ARCH=`uname -m`

SOURCE_DIRECTORY="$(dirname $(readlink -f $0))"
echo SOURCE_DIRECTORY=${SOURCE_DIRECTORY}

DATE=`date +"%Y%m%d%H%M%S"`

PACKAGE_NAME="digitallabboard"

#======================================================
# Create DEB file
#
makeDebFile() {

#   CP="cp -pv"
#   MKDIR="mkdir -pv"
#   RM="rm -f"
#   MV="mv -v"
#  GZIP="gzip -v"

   CP="cp -p"
   MKDIR="mkdir -p"
   RM="rm -f"
   MV="mv"
   GZIP="gzip"
   
   # Where to construct the install tree
   DUMMY_ROOT="${PACKAGE_NAME}_${VERSION}-${DEBIAN_VERSION}-${ARCH}"
   
   # Shared document files
   SHARED_DOC_DIR="${DUMMY_ROOT}/usr/share/doc/${PACKAGE_NAME}"
   
   DEB_DIR="${DUMMY_ROOT}/DEBIAN"
   RULES_DIR="${DUMMY_ROOT}/lib/udev/rules.d"
   BIN_DIR="${DUMMY_ROOT}/usr/bin"
#   LIB_DIR="${DUMMY_ROOT}/usr/lib"
#   LIB_PKG_DIR="${LIB_DIR}/${ARCH}-linux-gnu/${PACKAGE_NAME}"
   APPS_DIR="${DUMMY_ROOT}/usr/share/applications"
   APP_DIR="${DUMMY_ROOT}/usr/share/${PACKAGE_NAME}"   
   PIX_DIR="${DUMMY_ROOT}/usr/share/pixmaps"      
   if [[ -e ${DUMMY_ROOT} ]]; then
      ${RM} -R ${DUMMY_ROOT}
   fi
   
   ${MKDIR} ${DEB_DIR}
   ${MKDIR} ${RULES_DIR}
   ${MKDIR} ${BIN_DIR}
#  ${MKDIR} ${LIB_PKG_DIR}
   ${MKDIR} ${APPS_DIR}
   ${MKDIR} ${APP_DIR}
   ${MKDIR} ${PIX_DIR}

   ${CP} "${SOURCE_DIRECTORY}"/control ${DEB_DIR}  
   ${CP} "${SOURCE_DIRECTORY}"/*.rules ${RULES_DIR}   
   ${CP} -r "${SOURCE_DIRECTORY}/../PackageFiles/bin/${ARCH}-linux-gnu/." "${BIN_DIR}" 
#   ${CP} -rp "${SOURCE_DIRECTORY}/../Shared/${ARCH}-linux-gnu/." "${LIB_PKG_DIR}"   
   ${CP} -r "${SOURCE_DIRECTORY}"/*.desktop ${APPS_DIR}   
   ${CP} -r "${SOURCE_DIRECTORY}"/*.map ${APP_DIR}   
   ${CP} -r "${SOURCE_DIRECTORY}"/*.png ${PIX_DIR}   
   
 
   ${MKDIR} ${SHARED_DOC_DIR}
   ${GZIP} -n -9 -k -c "${SOURCE_DIRECTORY}/../PackageFiles"/changelog >${SHARED_DOC_DIR}/changelog.gz
   ${CP}    "${SOURCE_DIRECTORY}/../PackageFiles"/copyright             ${SHARED_DOC_DIR}

   # Fix permissions
   find ${DUMMY_ROOT}   -type d -exec chmod 755 {} \;
   find ${DUMMY_ROOT}   -type f -name \*.map\* -exec chmod 644 {} \;
   find ${DUMMY_ROOT}   -type f ! -executable -exec chmod 644 {} \;
   find ${DUMMY_ROOT}   -type f -name \*.so\* -exec chmod 644 {} \; -exec strip {} \;
   find ${DUMMY_ROOT}   -type f -executable -exec chmod 755 {} \; -exec strip {} \;
   
#   echo "ln -s ./${ARCH}-linux-gnu/${PACKAGE_NAME} ${DUMMY_ROOT}/usr/lib/${PACKAGE_NAME}"
#   ln -s ${ARCH}-linux-gnu/${PACKAGE_NAME} ${LIB_DIR}/${PACKAGE_NAME}

   echo fakeroot dpkg-deb --build ${DUMMY_ROOT}
   fakeroot dpkg-deb --build ${DUMMY_ROOT}

   echo lintian ${DUMMY_ROOT}.deb   
   lintian ${DUMMY_ROOT}.deb 

   ${RM} -R ${DUMMY_ROOT}

}

pausing() {
   x=10
   echo -n Pausing ...
   while [ $x -gt 0 ];  do
      sleep 1s
      echo -n " $x"
      x=$(( $x - 1 ))
   done
   echo 
}

# Build for native ARCH
makeDebFile

pausing
exit


